---
resources:
  - name: aviator
    type: git
    source: {uri: "https://github.com/AwesomeCICD/aviator"}

jobs:
  - name: build-js
    public: true
    plan:
      - task: build-js
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node}
          run:
            path: echo
            args: [hello world]

